export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCTS_SUCCESS: "SET_PRODUCTS_SUCCESS",
  SET_PRODUCTS_FAILED: "SET_PRODUCTS_FAILED",

  SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",
  SET_SELECTED_PRODUCT_SUCCESS: "SET_SELECTED_PRODUCT_SUCCESS",
  SET_SELECTED_PRODUCT_FAILED: "SET_SELECTED_PRODUCT_FAILED",

  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
